[package]
name = "teraflopter420"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"

[profile.release]
overflow-checks = false
codegen-units = 1

